# Outbound JSON Webhook Routing Module Interface
<integration>
  <name>shuffle</name>
  <hook_url>https://shuffler.io/api/v1/hooks/webhook_dafe5243-9071-4d75-80b5-4229f356e1ae</hook_url>
  <level>7</level>
  <alert_format>json</alert_format>
</integration>